import { delay, randomError } from '../utils';
import { mockEvents } from '../data/events';
import { mockAttendance } from '../data/attendance';
import { mockPhotos } from '../data/photos';
import { mockUsers } from '../data/users';
import { CreateEventDto } from '@/lib/types';

let events = [...mockEvents];
let attendance = [...mockAttendance];
let photos = [...mockPhotos];

export const eventMock = {
  getEvents: async (mahberId: string) => {
    await delay(600);
    const data = events.filter(e => e.mahber_id === mahberId);
    return {
      data: data.sort((a, b) => new Date(b.start_time).getTime() - new Date(a.start_time).getTime()),
      meta: { total: data.length, page: 1, limit: 20, totalPages: 1 },
    };
  },

  getEventById: async (mahberId: string, eventId: string) => {
    await delay(400);
    const event = events.find(e => e.mahber_id === mahberId && e.id === eventId);
    if (!event) throw new Error('Event not found');
    return event;
  },

  createEvent: async (mahberId: string, data: CreateEventDto) => {
    await delay(800);
    randomError(0.05);
    const newEvent = {
      id: `evt_${Date.now()}`,
      mahber_id: mahberId,
      title: data.title,
      description: data.description,
      event_type: data.event_type,
      start_time: data.start_time,
      end_time: data.end_time,
      location: data.location,
      is_mandatory: data.is_mandatory || false,
      is_cancelled: false,
      created_at: new Date().toISOString(),
    };
    events = [newEvent, ...events];
    return newEvent;
  },

  updateEvent: async (mahberId: string, eventId: string, data: Partial<CreateEventDto>) => {
    await delay(600);
    const index = events.findIndex(e => e.mahber_id === mahberId && e.id === eventId);
    if (index === -1) throw new Error('Event not found');
    events[index] = { ...events[index], ...data };
    return events[index];
  },

  cancelEvent: async (mahberId: string, eventId: string) => {
    await delay(700);
    const index = events.findIndex(e => e.mahber_id === mahberId && e.id === eventId);
    if (index === -1) throw new Error('Event not found');
    events[index].is_cancelled = true;
    return events[index];
  },

  getQRCode: async (mahberId: string, eventId: string) => {
    await delay(500);
    // Return a dummy data URI representing a mock QR code image. 
    // In a real app, this would be a real base64 image generated by the backend.
    return {
      qr_code: 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxNTAiIGhlaWdodD0iMTUwIiB2aWV3Qm94PSIwIDAgMTUwIDE1MCI+PHJlY3Qgd2lkdGg9IjE1MCIgaGVpZ2h0PSIxNTAiIGZpbGw9IiNmZmYiLz48cmVjdCB4PSIyMCIgeT0iMjAiIHdpZHRoPSIxMTAiIGhlaWdodD0iMTEwIiBmaWxsPSIjMDAwIi8+PHJlY3QgeD0iMzAiIHk9IjMwIiB3aWR0aD0iOTAiIGhlaWdodD0iOTAiIGZpbGw9IiNmZmYiLz48cmVjdCB4PSI0MCIgeT0iNDAiIHdpZHRoPSI3MCIgaGVpZ2h0PSI3MCIgZmlsbD0iIzAwMCIvPjwvc3ZnPg=='
    };
  },

  checkIn: async (mahberId: string, eventId: string, qrToken: string) => {
    await delay(1000);
    randomError(0.1);
    const newAttendance = {
      id: `att_${Date.now()}`,
      event_id: eventId,
      member_id: mockUsers[2].id, // Simulating a check-in from a specific user
      mahber_id: mahberId,
      checked_in_at: new Date().toISOString(),
      user: mockUsers[2],
    };
    attendance = [newAttendance, ...attendance];
    return newAttendance;
  },

  getPhotos: async (mahberId: string, eventId: string) => {
    await delay(600);
    const data = photos.filter(p => p.event_id === eventId);
    return {
      data,
      meta: { total: data.length, page: 1, limit: 20, totalPages: 1 },
    };
  },

  uploadPhoto: async (mahberId: string, eventId: string, formData: FormData) => {
    await delay(1200);
    // Simulate successful photo upload
    const newPhoto = {
      id: `pht_${Date.now()}`,
      event_id: eventId,
      mahber_id: mahberId,
      uploader_id: mockUsers[2].id,
      file_path: 'https://images.unsplash.com/photo-1491438590914-bc09fcaaf77a?q=80&w=800&auto=format&fit=crop',
      caption: formData.get('caption') as string || 'New photo upload',
      created_at: new Date().toISOString(),
      user: mockUsers[2],
    };
    photos = [newPhoto, ...photos];
    return newPhoto;
  },
};
