const CHAPA_EMAIL_MAX_LENGTH = 50;
const FALLBACK_DOMAIN = 'gmail.com';
const EMAIL_REGEX = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

/** Placeholder emails generated by the app — Chapa rejects these. */
function isSyntheticEmail(email: string): boolean {
  return /@mahberconnect\.com$/i.test(email);
}

/**
 * Chapa requires a valid email address with max length 50 characters.
 * The email domain must have valid MX records — Chapa validates server-side.
 * Use the user's real email when valid; otherwise a short deterministic fallback
 * using gmail.com which Chapa always accepts.
 */
export function toChapaEmail(
  email: string | null | undefined,
  userId: string,
): string {
  const trimmed = email?.trim();
  if (
    trimmed &&
    trimmed.length <= CHAPA_EMAIL_MAX_LENGTH &&
    EMAIL_REGEX.test(trimmed) &&
    !isSyntheticEmail(trimmed)
  ) {
    return trimmed;
  }

  const shortId = userId.replace(/-/g, '').slice(0, 8);
  return `mahber.pay.${shortId}@${FALLBACK_DOMAIN}`;
}
